### ISSUE TITLE
Blocking or non-blocking db calls?

### ISSUE THREAD

**Issue by dxxvi** [karimagnusson/kuzminki-zio#1]
Reading the README, I think this library uses jdbc inside (I might be very wrong)? But then I wonder, if this library uses jdbc inside, then why supporting postgresql only? And now I'm confused.

**Comment by karimagnusson** [comment]
It uses jdbc and the calls are made in ZIOs blocking thread pool. Currently it is only for Postgres, but then I only just released it. If I find there is interest in using it for other databases I may well add support for them.
